--[[
Converts ```console code blocks to Quarto-compatible terminal-styled blocks.

Generated by claude-sonnet-4-6 
--]]

function CodeBlock(el)
    -- Guard: return unchanged if no classes are present
    if not el.classes or #el.classes == 0 then
        return el
    end

    if el.classes:includes("console") then
        -- Replace `console` with `bash` and add a terminal filename label
        el.classes = el.classes:filter(function(c) return c ~= "console" end)
        el.classes:insert("bash")
        el.attributes["filename"] = "Terminal"
        return el
    end
end