--[[
Converts GitHub Markdown callout blockquotes to Quarto callout divs.

GitHub style:
> [!NOTE]
> This is a note

Quarto style:
::: {.callout-note}
This is a note
:::

Generated by claude-sonnet-4-6
--]]

-- Mapping from GitHub callout types to Quarto callout types
local callout_map = {
    NOTE      = "callout-note",
    TIP       = "callout-tip",
    IMPORTANT = "callout-important",
    WARNING   = "callout-warning",
    CAUTION   = "callout-caution",
}

function BlockQuote(el)
    -- Check if the first block is a paragraph starting with [!TYPE]
    if #el.content == 0 then return el end

    local first = el.content[1]
    if first.t ~= "Para" then return el end
    if #first.content == 0 then return el end

    local first_inline = first.content[1]
    if first_inline.t ~= "Str" then return el end

    -- Match [!NOTE], [!TIP] etc.
    local callout_type = first_inline.text:match("^%[!(%u+)%]$")
    if not callout_type then return el end

    local quarto_type = callout_map[callout_type]
    if not quarto_type then return el end

    -- Remove the [!TYPE] line from the content
    local remaining = {}
    for i, block in ipairs(el.content) do
        if i == 1 then
            -- Remove the first inline ([!TYPE]) and any trailing softbreak
            local new_inlines = {}
            for j, inline in ipairs(first.content) do
                if j > 1 then
                    -- Skip leading SoftBreak after the type marker
                    if j == 2 and inline.t == "SoftBreak" then
                    else
                        table.insert(new_inlines, inline)
                    end
                end
            end
            if #new_inlines > 0 then
                table.insert(remaining, pandoc.Para(new_inlines))
            end
        else
            table.insert(remaining, block)
        end
    end

    -- Wrap in a Quarto callout div
    return pandoc.Div(remaining, pandoc.Attr("", {quarto_type}))
end